import type { NextPage } from "next";
import Head from "next/head";
import BasicLayout from "layout/Basic";

const Home: NextPage = () => {
  return (
    <BasicLayout>
      <Head>
        <title>Baxhen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </BasicLayout>
  );
};

export default Home;
