import type { Message } from "./useInvisibilityDossier.types";

export const NEXT_ROUTE = "/";

export const EVIDENCE_AUDIO_PATH = "/audios/what-just-happened.mp3";

export const SHORT_DELAY = 800;
export const AUDIO_DELAY = 1000;
export const CASE_FILE_DELAY = 1200;
export const PDF_DOCUMENT_DELAY = 1200;
export const TRANSITION_DURATION = 600;

const padTime = (n: number): string => String(n).padStart(2, "0");

const t = (h: number, m: number): string => `${padTime(h)}:${padTime(m)}`;

// NOTE: create a realistic timeline make a hook for it later;
const T = {
  t1: t(19, 42),
  t2: t(19, 42),
  t3: t(19, 43),
  t4: t(19, 43),
  t5: t(19, 44),
  t6: t(19, 44),
  t7: t(19, 45),
  t8: t(19, 46),
  t9: t(19, 47),
  t10: t(19, 47),
  t11: t(19, 48),
  t12: t(19, 49),
  t13: t(19, 49),
  t14: t(19, 50),
  t15: t(19, 50),
  t16: t(19, 51),
  t17: t(19, 51),
  t18: t(19, 52),
  t19: t(19, 52),
  t20: t(19, 53),
  t21: t(19, 53),
};

export const SCRIPT: Message[] = [
  {
    id: 1,
    type: "text",
    sender: "baxhen",
    text: "The report has been delivered.",
    timestamp: T.t1,
    status: "read",
  },
  {
    id: 2,
    type: "text",
    sender: "baxhen",
    text: "I've reviewed the findings.",
    timestamp: T.t2,
    status: "read",
  },
  {
    id: 3,
    type: "text",
    sender: "baxhen",
    text: "And honestly...",
    timestamp: T.t3,
    status: "read",
  },
  {
    id: 4,
    type: "text",
    sender: "baxhen",
    text: "The results were disturbing.",
    timestamp: T.t4,
    status: "read",
  },
  {
    id: 5,
    type: "text",
    sender: "baxhen",
    text: "I'm sending you the same evidence.",
    timestamp: T.t5,
    status: "read",
  },
  {
    id: 6,
    type: "text",
    sender: "baxhen",
    text: "Listen carefully.",
    timestamp: T.t6,
    status: "read",
  },
  {
    id: 7,
    type: "audio",
    sender: "baxhen",
    title: "WHAT JUST HAPPENED?",
    duration: "0:20",
    audioSrc: "/audios/what-just-happened.mp3",
    timestamp: T.t7,
    status: "read",
  },
  {
    id: 8,
    type: "text",
    sender: "baxhen",
    text: "Let's start.",
    timestamp: T.t8,
    status: "read",
  },
  {
    id: 9,
    type: "pdf-document",
    sender: "baxhen",
    title: "Case File #1",
    pdfFilename: "The Memory Problem",
    pdfPageCount: "3",
    pdfFileSize: "1.2 MB",
    timestamp: T.t9,
    status: "read",
  },
  {
    id: 10,
    type: "text",
    sender: "baxhen",
    text: "This is where things got interesting.",
    timestamp: T.t10,
    status: "read",
  },
  {
    id: 11,
    type: "text",
    sender: "baxhen",
    text: "This isn't an isolated case. It's an epidemic.",
    timestamp: T.t11,
    status: "read",
  },
  {
    id: 12,
    type: "audio",
    sender: "baxhen",
    title: "THE EPIDEMIC",
    duration: "0:23",
    audioSrc: "/audios/the-epidemic.mp3",
    timestamp: T.t12,
    status: "read",
  },
  {
    id: 13,
    type: "text",
    sender: "baxhen",
    text: "And then I found the pattern.",
    timestamp: T.t13,
    status: "read",
  },
  {
    id: 14,
    type: "audio",
    sender: "baxhen",
    title: "THE DISCOVERY",
    duration: "0:18",
    audioSrc: "/audios/the-discovery.mp3",
    timestamp: T.t14,
    status: "read",
  },
  {
    id: 15,
    type: "text",
    sender: "baxhen",
    text: "And that's when everything changed.",
    timestamp: T.t15,
    status: "read",
  },
  {
    id: 16,
    type: "audio",
    sender: "baxhen",
    title: "THE REVEAL",
    duration: "0:25",
    audioSrc: "/audios/the-reveal.mp3",
    timestamp: T.t16,
    status: "read",
  },
  {
    id: 17,
    type: "text",
    sender: "baxhen",
    text: "One final take.",
    timestamp: T.t17,
    status: "read",
  },
  {
    id: 18,
    type: "audio",
    sender: "baxhen",
    title: "THE DEMONSTRATION",
    duration: "0:28",
    audioSrc: "/audios/the-demonstration.mp3",
    timestamp: T.t18,
    status: "read",
  },
  {
    id: 19,
    type: "text",
    sender: "baxhen",
    text: "If you're ready...",
    timestamp: T.t19,
    status: "read",
  },
  {
    id: 20,
    type: "text",
    sender: "baxhen",
    text: "I'll show you how we build these experiences.",
    timestamp: T.t20,
    status: "read",
  },
  {
    id: 21,
    type: "button",
    sender: "baxhen",
    text: "ACCESS THE REVELATION",
    timestamp: T.t21,
  },
];
